baseURL: http://example.org/
languageCode: en-us
title: Loving my tummy
theme: summer-qremix
params:
  tagline: Loving my tummy
  copyright: >-
    © 2024 [José Miguel Horcas](https://sites.google.com/view/josemiguelhorcas)
  links:
    - name: GitHub
      url: https://github.com/lovingmytummy/lovingmytummy.github.io
    - name: The Quiqr Book
      url: https://book.quiqr.org
  moreLinksTitle: More Themes
  moreLinks:
    - name: Spring
      url: https://connor-baer.github.io/spring
    - name: Autumn
      url: https://connor-baer.github.io/autumn
  color: blue
  font: Acme
  resources: []
  header_image: index-large.jpeg
  logo_image: logo.svg
  favicon_image: favicon.png
markup:
  goldmark:
    renderer:
      unsafe: true
